services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rotary_app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - APP_NAME=Rotary
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - APP_KEY=base64:/cLNz2MzWnxFTpYX9yf2jPHI0VSdLkTve/AeDKl7I/M=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - SESSION_DRIVER=file
      - CACHE_STORE=file
      - QUEUE_CONNECTION=sync
      - RUN_MIGRATIONS=true
    volumes:
      - sqlite_data:/var/www/html/database

volumes:
  sqlite_data:
